=== codemunki/codemunki-work/minimud/world_data.dtd
<!ELEMENT minimud_world (room+)>

<!ELEMENT room (id, name, description, move+, npc*, object* ) >

<!ELEMENT id (#PCDATA)>
<!ELEMENT item_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT move ( direction, next_room_id, description )>

<!ELEMENT direction (#PCDATA)>
<!ELEMENT next_room_id (#PCDATA)>

<!ELEMENT object (name, description, action*)>
<!ELEMENT npc (name, description, intro, action*)>
<!ELEMENT action (name, result)>

<!ELEMENT intro (#PCDATA)>
<!ELEMENT detail (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT result (type, description, item_id?, value?)>

=== codemunki/codemunki-work/minimud/world_data.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE minimud_world SYSTEM "world_data.dtd">

<minimud_world>
	<room>
		<id>1</id>
		<name>Starter Tavern</name>
		<description>You appear in a dark, smelly tavern.  You can't pick out any specific conversation amongst the cacophony, but you're sure it's there.  The exit to the street is to the west.  There is a rusty lantern on the table in front of you.  What looks like a door to a storeroom is to the north.</description>
		<move>
			<direction>west</direction>
			<next_room_id>2</next_room_id>
			<description>Street exit</description>
		</move>
		<move>
			<direction>north</direction>
			<next_room_id>3</next_room_id>
			<description>Storeroom door</description>
		</move>
		<npc>
			<name>Tommy</name>
			<description>a tall, scruffy man in a brown leather jerkin.  He looks a little drunk, but otherwise harmless.  He looks like he has something to say.</description>
			<intro>Name's Tommy the Lip, but you can call me Tommy.  Welcome to the world of MiniMUD.  I can answer most basic questions that new folks tend to ask.</intro>
			<action>
				<name>punch</name>
				<result>
					<type>text_only</type>
					<description>You try to punch Tommy the Lip, but miss.  Maybe he's not as drunk as he looks.</description>
				</result>
			</action>
			<action>
				<name>push</name>
				<result>
					<type>text_only</type>
					<description>You push Tommy.  He didn't appear to enjoy it as much as you did.</description>
				</result>
			</action>
		</npc>
		<object>
			<name>lantern</name>
			<description>a standard oil-based lantern, covered in rust.  It must not be important to anyone.</description>
			<action>
				<name>push</name>
				<result>
					<type>text_only</type>
					<description>You push the lantern and it falls over.</description>
				</result>
			</action>
		</object>
	</room>

	<room>
		<id>2</id>
		<name>Main Street</name>
		<description>You turn on to Main Street.  There isn't much traffic this time of day.  To the east is a loud, smelly tavern.</description>
		<move>
			<direction>east</direction>
			<next_room_id>1</next_room_id>
			<description>Tavern door</description>
		</move>			
	</room>

	<room>
		<id>3</id>
		<name>Storeroom</name>
		<description>You quietly sneak into the storeroom.  It is lined with the skulls of sacrificed animals.  There is a pentagram painted on the floor in blood.  You wonder what exactly is in the meat pie.  To the south is the door back into the main Tavern.</description>
		<move>
			<direction>south</direction>
			<next_room_id>1</next_room_id>
			<description>Tavern door</description>
		</move>			
	</room>
</minimud_world>
